### ISSUE TITLE
Cloudflare Auth not possible with 2FA activated

### ISSUE THREAD

**Issue by g4njawizard** [ddclient/ddclient#412] opened 2022-05-06 05:18 UTC
Hi,
I try to switch on OPNsense from dyndns to ddclient and I noticed that I am unable to log into my account, when I am using 2FA on cloudflare. 
Users should be able to use a token based auth method.

**Comment by SuperSandro2000** [comment] 2022-05-12 22:25
Dupe of #361

**Closed by SuperSandro2000** 2022-05-12 22:25 UTC
