### ISSUE TITLE
Invalid Value for keyword 'ip' = ''

### ISSUE THREAD

**Issue by gforschi** [ddclient/ddclient#467] opened 2022-10-16 19:49 UTC
I can't seem to be able to use this plugin with OpnSense and Cloudflare.

**Comment by kangaroo72** [comment] 2022-10-17 10:40
Actually my system is down, but 2 weeks ago my system worked with cloudflare.
I had to change [this](https://github.com/ddclient/ddclient/pull/343/commits/ed128a0b99a5fbf2d3aab10320922c24c4364f6a)

**Comment by SuperSandro2000** [comment] 2022-10-30 22:46
Dupe of #307

**Closed by SuperSandro2000** 2022-10-30 22:46 UTC
Labels: bug, packaging
