### ISSUE TITLE
Cloudflare headers not stripped correctly

### ISSUE THREAD

**Issue by x2a-io** [ddclient/ddclient#347] opened 2021-07-11 05:17 UTC
The Cloudflare headers contain an extra line before the json body (Length of the body in hex). See an example from my logs below:
```
RECEIVE:  HTTP/1.1 200 OK
RECEIVE:  Date: ...
RECEIVE:  Content-Type: application/json
RECEIVE:  Transfer-Encoding: chunked
RECEIVE:  Connection: close
RECEIVE:  CF-Ray: ...
RECEIVE:  Set-Cookie: __cflb=...; SameSite=Lax; path=/; expires=...; HttpOnly
RECEIVE:  Vary: Accept-Encoding
RECEIVE:  CF-Cache-Status: DYNAMIC
RECEIVE:  Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
RECEIVE:  x-envoy-upstream-service-time: 2
RECEIVE:  Set-Cookie: __cfruid=...; path=/; domain=.api.cloudflare.com; HttpOnly; Secure; SameSite=None
RECEIVE:  Server: cloudflare
RECEIVE:  
RECEIVE:  221
RECEIVE:  {"result":[{"id":"...","zone_id":"....","zone_name":"...","name":"...","type":"A","content":"...","proxiable":true,"proxied":false,"ttl":1,"locked":false,"meta":{"auto_added":false,"managed_by_apps":false,"managed_by_argo_tunnel":false,"source":"primary"},"created_on":"...","modified_on":"..."}],"success":true,"errors":[],"messages":[],"result_info":{"page":1,"per_page":20,"count":1,"total_count":1,"total_pages":1}}
RECEIVE:  0
RECEIVE:
```

The current logic for stripping headers (`$reply =~ s/^.*?\n\n//s;`) does not remove these extra lines, resulting in json parsing errors.

I'm not super familiar with perl, but my proposed solution (and what currently works for me) is something along the lines of:
```
# Strip header
$reply =~ s/^.*?\n\n[0-9a-fA-F]+\n//s;
# Strip footer
$reply =~ s/\d+\n\n$//s;
```

**Comment by zraexy** [comment] 2021-07-12 05:49
This is a duplicate of #338, which was caused by #333.

**Closed** 2022-03-19 19:19 UTC
