### ISSUE TITLE
dnsomatic - lots of warnings/errors?

### ISSUE THREAD

**Issue by madchap** [ddclient/ddclient#497] opened 2023-01-09 00:25 UTC
Hi,

Using ddclient v3.10.0 on aarch64 (trying to get an [add-on](https://github.com/madchap/addon-ddclient) running for hassio).

I am getting a lot of warnings:
```
FAILED:   updating all.dnsomatic.com: unexpected status (13)
Use of uninitialized value $h in hash element at /usr/bin/ddclient line 4101.
Use of uninitialized value $h in hash element at /usr/bin/ddclient line 4103.
Use of uninitialized value $h in hash element at /usr/bin/ddclient line 4104.
Use of uninitialized value $_[0] in sprintf at /usr/bin/ddclient line 2160.
SUCCESS:  updating : good: IP address set to 178.x.x.x
Use of uninitialized value $h in hash element at /usr/bin/ddclient line 4101.
Use of uninitialized value $_[0] in sprintf at /usr/bin/ddclient line 2160.
FAILED:   updating : unexpected status (0)
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
Use of uninitialized value in string ne at /usr/bin/ddclient line 1154.
FAILED:    was not updated because protocol <undefined> is not supported
```

Configuration is like:
```
daemon=900                                                                                       
syslog=yes                                                                                 
mail=root                                                                                         
mail-failure=root                                                                             
pid=/run/ddclient/ddclient.pid                                                                                  
ssl=yes

# dnsomatic
use=web, web=myip.dnsomatic.com
server=updates.dnsomatic.com,      \
protocol=dyndns2,                  \
login=xxxxxxx,          \
password=xxxxxx        \
all.dnsomatic.com
```

Thanks for the work and help!
Cheers.

**Comment by SuperSandro2000** [comment] 2023-01-13 17:50
dupe of #386

**Closed by SuperSandro2000** 2023-01-13 17:50 UTC
Labels: bug, enhancement, help-wanted
