### ISSUE TITLE
ddclient v3.11.2/opnsense plugin os-ddclient v1.21 - ddclient updates GoDaddy DNS entry every 300s even if dynamic IP has not changed

### ISSUE THREAD

**Issue by phaze75** [ddclient/ddclient#631] opened 2024-02-21 17:40 UTC
Hi there,

I am submitting this issue after unsuccessfully resolving it via the opnsense/plugins/os-ddclient repository: [https://github.com/opnsense/plugins/issues/3805](https://github.com/opnsense/plugins/issues/3805)

To be frank, things unfortunately escalated there, after I criticized the -from my point of view- lack of support. So, to prevent repeating any potential mistakes made, I would like to state upfront:

- I am not a technical expert, my skills are limited
- I am a very happy home user of opnsense and ddclient
- I seek support and help here to solve my problem and hopefully contribute a bit to solving it for the rest of the community
- I am very grateful for any help given

In order to limit the redundancies, I will just copy and paste the description of the issue here. More detailed information is to be found in the link above.

**Describe the bug**

I just changed my ddclient from using FreeDNS to using GoDaddy. The dynamic ip has been checked properly (via Interface/WAN) and the respective GoDaddy DNS entry has been updated correctly. However, ddclient now seems to "statically/periodically" update the GoDaddy DNS entry every 300 seconds (as configured in ddclient's general settings), even if the dynamic ip has not changed.

ddclient using GoDaddy now shows a different behavior compared to using FreeDNS. Using FreeDNS, the DNS entry was only updated if the dynamic IP had been changed by the provider.

Best regards!

**Comment by LenardHess** [comment] 2024-02-25 17:02
Hello,

I am not familiar with opnsense - skimming through they seem to have layered a GUI and json-based config format on top of ddclient.

Could you either locate and share the ddclient.conf file, the json config file from opnsense or your exact settings including any generic DynDNS settings there may be (I saw the ddclient.conf template mention stuff like `OPNsense.DynDNS.general.allowipv6`)

**Comment by phaze75** [comment] 2024-02-26 10:20
Hello,

thank you for reaching out to me. My ddclient.conf looks like this:

```console
root@OPNsense:~ # cat /usr/local/etc/ddclient.conf
syslog=yes                  # log update msgs to syslog
pid=/var/run/ddclient.pid   # record PID in file.
verbose=yes
ssl=yes

usev4=ifv4, ifv4=igb0, \
protocol=godaddy, \
zone=xxxx.xx, \
login=xxxxxxxxxxxxxxxxxxxxxx, \
password=xxxxxxxxxxxxxxxxxxxx \
xxxxxx.xxxx.xx
root@OPNsense:~ #
```
In the "General settings" the interval to check for address changes is set to 300s (the interval in which Godaddy is currently updated):

![image](https://github.com/ddclient/ddclient/assets/2933023/b453c5c1-0fa8-46a2-b843-caccd31e2c2d)

Best regards!

**Comment by phaze75** [comment] 2024-04-02 07:43
@LenardHess Is there anything more that I could provide?

**Comment by LenardHess** [comment] 2024-04-04 20:47
This should be sufficient, thanks - I simply haven't gotten around to taking a look at this

**Comment by rhansen** [comment] 2024-05-18 07:26
duplicate of #554

**Closed** 2024-05-23 05:53 UTC
Labels: bug
