### ISSUE TITLE
[request] new freedns (afraid.org) v2 api support

### ISSUE THREAD

**Issue by atesin** [ddclient/ddclient#440] opened 2022-07-30 06:31 UTC
hi... afraid.org has a new more secure, easy, and efficient api, mentioned here -> http://freedns.afraid.org/dynamic/v2/ (need login to see it)

firstly, i have no idea about perl, and i had never send a patch/pull request before, so i will try to explain this new v2 api clear and easy...

i will explain below how to get it, but basically you will get and use just a random token instead all your account and domain data embedded in url... the new v2 url is shorter and your data is not exposed at all...

- having your random token {randomToken} and your new ip address {newIp}, go one of these urls:
  - _http://sync.afraid.org/u/{randomToken}/_
  - _http://sync.afraid.org/u/{randomToken}/?address={newIp}_
  - _https://sync.afraid.org/u/{randomToken}/_
  - _https://sync.afraid.org/u/{randomToken}/?address={newIp]_
  -  NOTES: i didn't tested https, i think new ip is detected by web but `?address={newIp}` seems optional, not tested either, i saw this in openwrt `ddns-scripts` package
- then the system answers with one of these responses **as i tested** (didn't covered all posibilities though) (plain text?, all http statuses _200 OK_?)
  - `Updated {yourDomain} from {oldIp} to {newIp}`
  - `No IP change detected for {yourDomain} with IP {newIp}, skipping update`
  - `Couldn't find any matching DNS records via randomkey method!`

very easy right?... now i will explain how to enable api v2 on your freedns domains (need login _afraid.org_ frist)

- once you **logged in** and go to http://freedns.afraid.org/dynamic/v2/ you will see 4 different update methods, this info is about the first shown method, the default, simple, secure and joshua's favorite, labeled as "_randomized update token_"
- at the bottom you will see 2 lists, one below the other, the upper one has your v2 enabled domains, and the lower has your not yet v2 enabled
- you can enable/disable v2 api support on domains by moving them between lists, by select domains with the leading checkbox, choosing the dropdown select action (enable or disable ddns v2) and clicking the "_apply_" button
- once domains are enabled for v2 ddns api, the system generates a random token and associates with your domain/acount and everyting, so is the only info you need (side note: changing your method at top will update the domain urls below)

### additional useful but not strictly related information

afraid.org freedns also have its own checkip url = `http://freedns.afraid.org/dynamic/check.php` (also https?)...   but instead i use port 8080 that i think is better, this is why...

i remembered once i got late with my internet payment, so my isp redirected all my web traffic to some captive "_service disabled, pay here_" webpage...  the rest of my services seem to work fine (ssh, vpn, minecraft server, personal docs, etc)... BUT they couldn't be reached because my ip isp redirected all ddns urls to "_service disabled, pay here_"... i was far from city and needed to access my (banking) docs through vpn to pay the bill and restore the service :/

was an oddyssey, i spent all the weekend without being able to connect my house and _work_ ;).... next monday when i finally could pay the bill and restore the service i contacted afraid.org admin and explained the situation... so thinking this could happen to somebody else in the future, he **kindly** opened additional port 8080 on his webserver as additional port for ddns service :D

now i use this more bulletproof check ip url `http://freedns.afraid.org:8080/dynamic/check.php` instead

**Comment by NvrBst** [comment] 2022-09-09 07:58
yes, this is a duplicate of #420 . I just mention it, so when it gets implemented, both these issues may be closed. FreeDNS is a very popular DDNS, and the token-based auth is the main way to update these URLs now (been so for many years).

**Comment by user111222333** [comment] 2022-10-22 20:36
Hello dev team of os-ddclient
I am using os-ddclient v.1.9 installed from repository managed by the OPNsense team. 
It does not appear that the v1.9 written in a way that allows to 'easily' to configure the ddns sync with a service freedns.afraid.org
Could you please consider working with the system admin of freedns.afraid.org to include the template with the os-ddclient. 

Could anyone please provide a suggestion what and if it is at all possible to get the os-ddclient v.1.9 to work with freedns.afraid.org at all? I could not get it to work even with the previously used token method.

**Comment by atesin** [comment] 2022-10-23 05:53
you could try `ddupdate` instead ... i just wrote an afraid.org v2 plugin a few days ago (hope gets approved)... (sorry but i don't know a bit of perl)

ddupdate is different...  is modular (plugin based), written in python, and fairly new....  if you don't mind to risk with this new kid on the block you could try it (no warranties assumed)... if you regret you can always come back, like me i am a ddclient user from decades

**Closed** 2023-03-14 13:41 UTC
Labels: enhancement, provider, help-wanted
