### ISSUE TITLE
ddclient-3.10.0: Use of uninitialized value in string ne at /usr/bin/ddclient line 1154

### ISSUE THREAD

**Issue by m1027** [ddclient/ddclient#498] opened 2023-01-19 19:39 UTC
Hi,

I am seeing the above error message during operation with ddclient-3.10.0 on Gentoo Linux. FYI, this is the line: ```next if $config{$h}{'protocol'} ne lc($s);```

Thanks

**Comment by SuperSandro2000** [comment] 2023-02-08 12:37
dupe of #386

**Closed by SuperSandro2000** 2023-02-08 12:37 UTC
