### ISSUE TITLE
./autogen error

### ISSUE THREAD

**Issue by unclehowell** [ddclient/ddclient#313] opened 2021-02-27 01:10 UTC
Unescaped left brace in regex is passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /usr/local/bin/automake line 3936.
configure.ac:14: installing 'build-aux/install-sh'
configure.ac:14: installing 'build-aux/missing'
autoreconf: Leaving directory `.'

**Comment by rrthomas** [comment] 2021-03-06 15:27
This is not a bug in ddclient, it's a deprecation warning (or possibly error if you have Perl >= 5.32) about automake.

**Comment by unclehowell** [comment] 2021-03-06 20:50
Thanks. So what solution do you suggest ?

**Comment by rrthomas** [comment] 2021-03-06 20:56
If it's a warning, then there's no problem. (I didn't see an error message.)

If it's an error, upgrade automake.

**Comment by wimpunk** [comment] 2021-03-26 16:12
@unclehowell , can we close this issue?

**Closed** 2022-05-15 20:39 UTC
Labels: question
