### ISSUE TITLE
Make a release please

### ISSUE THREAD

**Issue by SimonMcN** [ddclient/ddclient#457] opened 2022-09-16 12:04 UTC
It has been over 2 and a half years since the last release.  Linuxserver.io only build docker images based on releases.

I need the cloudflare changes that have been in the repo for 2 years or so.

Please can you do a release ?
Cheers
Simon

**Comment by SuperSandro2000** [comment] 2022-09-16 13:44
dupe of #429

**Closed by SuperSandro2000** 2022-09-16 13:44 UTC
