### ISSUE TITLE
generic Link URL protocol?

### ISSUE THREAD

**Issue by shawndalton** [ddclient/ddclient#418] opened 2022-06-01 06:14 UTC
Im using dirctnic.com which offers a link to change an IP dynamically:

https://directnic.com/dns/gateway/{SECURECODEFORDOMAIN}/?data={IP_ADDRESS}

Is there a protocol i should use or a way to build this link?

**Comment by Moskito99** [comment] 2022-08-08 14:11
Please add support for URL update.
I use a script which updated a PowerDNS Domain only via URL.

**Comment by SuperSandro2000** [comment] 2022-08-16 12:10
dupe of #270

**Closed by SuperSandro2000** 2022-08-16 12:10 UTC
Labels: provider, help-wanted
