### ISSUE TITLE
Version bump for Cloudflare API Token support

### ISSUE THREAD

**Issue by ZLima12** [ddclient/ddclient#361] opened 2021-09-17 22:52 UTC
I just went through a whole bunch of digging to figure out why cloudflare updates weren't working for me. I wound up finding that the API token wasn't being set in the headers properly, and hacked in an edit for my setup. I then checked this repository, so I could submit a PR to fix this, only to find via git bisect that it was fixed almost a year and a half ago in 18cc3a9.

Could there be a version bump that includes this commit? Having Cloudflare support broken for so long seems like a big issue.

**Comment by thatnerdjosh** [comment] 2021-10-05 23:59
+1 I discovered this as well this morning. Seems that it is sending `X-Auth-Key` rather than `Authorization`

**Comment by Wireheadbe** [comment] 2021-12-27 18:16
Anyway to get this version bumped? Cloudflare support is lacking at this point

**Comment by DaveSophoServices** [comment] 2021-12-27 18:32
There’s only one or two who have write access to master. They don’t appear to be responding.

**Comment by kpostekk** [comment] 2022-01-03 14:10
If someone need DDNS for cloudfare ASAP, this repo looks like a solution for them https://github.com/timothymiller/cloudflare-ddns

**Comment by abelfodil** [comment] 2022-01-08 05:14
Using the Global API Token fixes it for the 3.9.1 version

**Comment by pgrenaud** [comment] 2022-01-23 21:40
Cloudflare protocol does work in the latest release, but only with the global API key. So yeah, not ideal. I would much rather use an API token instead.

**Comment by PHLAK** [comment] 2022-02-08 15:32
I've also been waiting on this for a while (#272). :slightly_frowning_face:

**Comment by NNTin** [comment] 2022-04-24 17:25
> Cloudflare protocol does work in the latest release, but only with the global API key. So yeah, not ideal. I would much rather use an API token instead.

This worked for me. Hoping this gets fixed soon, then I'll switch to API token.

**Comment by SuperSandro2000** [comment] 2022-05-15 21:06
3.10.0rc1 is out now. Can you try that version, please

**Comment by apbarratt** [comment] 2022-05-19 13:09
I'm at a loss for how to actually try the new versions.  The tutorials for installing them seem to just have me get the source code and then run commands that error out :(

**Comment by apbarratt** [comment] 2022-05-19 13:18
For example, if I clone the repo, it says the first thing I need to do is run `./autogen`.  For me, I just get this error:
```
apbarratt@lenovo:~/ddclient$ ./autogen
./autogen: 7: autoreconf: not found
ERROR: 'autoreconf -fviW all' failed
```

**Comment by apbarratt** [comment] 2022-05-19 13:28
You're quite right.  Fixed that and it's building now.  Before I continue, thought I'd share the summary of the testsuite before I forget (this is from latest of master branch):
```
============================================================================
Testsuite summary for ddclient 3.10.0_2
============================================================================
# TOTAL: 57
# PASS:  52
# SKIP:  3
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 1
```

and the tests in question:
``` 
FAIL: t/get_ip_from_if.pl 3 - Get default interface and IP for test system
ERROR: t/get_ip_from_if.pl - exited with status 1
```

Don't know if this is of interest to you or not, just figured I'd share :)

**Comment by apbarratt** [comment] 2022-05-19 13:38
Okay, so I'm now hitting a new error, not with cloudflare but with checkip.dyndns.org:
```
CONNECT:  checkip.dyndns.org
WARNING:  cannot connect to checkip.dyndns.org:443 socket: SSL connect attempt failed SSL connect attempt failed
WARNING:  found neither IPv4 nor IPv6 address
WARNING:  MYDOMAINNAME.TLD: unable to determine IP address with strategy use=web
```
Indeed, I can confirm that I hit a 404 if I try to get my IP over https rather than http from checkip.dyndns.org
Has something changed here recently?

**Comment by apbarratt** [comment] 2022-05-19 13:56
Have we a discord or similar anywhere?  Might make working on this faster for you if I hear it pinging at me for attention, here to test and prod if you need me 😅

**Comment by SuperSandro2000** [comment] 2022-05-25 22:55
> Don't know if this is of interest to you or not, just figured I'd share :)

Are there any more information in the log?
What system and version of it are you running?

> Indeed, I can confirm that I hit a 404 if I try to get my IP over https rather than http from checkip.dyndns.org

I don't understand how any service on the internet does not have TLS in 2022.

I think if you set ``ssl=yes`` then everything enforces https.

Can you try ``http://ipv4.nsupdate.info/myip`` instead?

> Back to cloudflare not liking me

I am using cloudflare, too and for me it works. I think I am using some global token and just threw it into password and that apparently works.

> Have we a discord or similar anywhere?

Not really and I don't really have time to also maintain that.

**Comment by haifisch88** [comment] 2022-06-08 08:56
Any update on this? How can I use my API Token now? I really dont want to use the Global API Key

**Comment by SuperSandro2000** [comment] 2022-06-11 12:08
Please try the 3.10.0 pre release. It should work with that.

**Comment by MBfromOK** [comment] 2022-06-28 22:16
I am using OPNsense 22.1.9_1 and would be willing to test this but would need a tarfile with all the required packages ./autogen failed when I tried.

(or could you push it to freebsd.ports?)

**Comment by retep** [comment] 2022-06-29 09:18
@SuperSandro2000 - I too am using OPNsense 22.1.9_1 and would be willing to test, but I need support for Mythic Beasts which has had a PR hanging around for quite a while.  Any chance on getting this merged?
TIA

**Comment by nkfs** [comment] 2022-08-10 18:45
> Please try the 3.10.0 pre release. It should work with that.

Still returning the invalid error with 3.10.0_2

ddclient  | RECEIVE:  {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6103,"message":"Invalid format for X-Auth-Key header"}]}],"messages":[],"result":null}

**Comment by Christophe999s** [comment] 2022-08-22 06:29
You have to use the global API key, or if you're using a token, give it edit AND read access to the zone.
That solved the issue for me.

**Comment by Christophe999s** [comment] 2022-08-27 12:04
It seems I was a bit too soon with my comment, it seemed to work but as soon the ddclient restarted an my IP changed, the same error was back :/

**Comment by cmcasanova** [comment] 2022-09-09 22:12
Updated to 3.10.0_2 on ubuntu 20.04 and getting this...

sudo ddclient -daemon=0 -debug -verbose -noquiet
=== opt ====
opt{cache}                           : <undefined>
opt{cmd}                             : <undefined>
opt{cmd-skip}                        : <undefined>
opt{cmdv4}                           : <undefined>
opt{cmdv6}                           : <undefined>
opt{curl}                            : <undefined>
opt{daemon}                          : 0
opt{debug}                           : 1
opt{exec}                            : <undefined>
opt{facility}                        : <undefined>
opt{file}                            : <undefined>
opt{force}                           : <undefined>
opt{foreground}                      : <undefined>
opt{fw}                              : <undefined>
opt{fw-banlocal}                     : CODE(0x561836242020)
opt{fw-login}                        : <undefined>
opt{fw-password}                     : <undefined>
opt{fw-skip}                         : <undefined>
opt{fw-ssl-validate}                 : <undefined>
opt{fwv4}                            : <undefined>
opt{fwv4-skip}                       : <undefined>
opt{fwv6}                            : <undefined>
opt{fwv6-skip}                       : <undefined>
opt{geturl}                          : <undefined>
opt{help}                            : <undefined>
opt{host}                            : <undefined>
opt{if}                              : <undefined>
opt{if-skip}                         : CODE(0x561836242020)
opt{ifv4}                            : <undefined>
opt{ifv6}                            : <undefined>
opt{ip}                              : <undefined>
opt{ipv4}                            : <undefined>
opt{ipv6}                            : <undefined>
opt{list-devices}                    : CODE(0x5618364a56d8)
opt{list-protocols}                  : CODE(0x5618364a5870)
opt{list-web-services}               : CODE(0x5618364b0e40)
opt{login}                           : <redacted>
opt{mail}                            : <undefined>
opt{mail-failure}                    : <undefined>
opt{max-interval}                    : 2160000
opt{max-warn}                        : <undefined>
opt{min-error-interval}              : 300
opt{min-interval}                    : 30
opt{options}                         : <undefined>
opt{password}                        : <redacted>
opt{pid}                             : <undefined>
opt{postscript}                      : <undefined>
opt{priority}                        : <undefined>
opt{protocol}                        : <undefined>
opt{proxy}                           : <undefined>
opt{query}                           : <undefined>
opt{quiet}                           : 0
opt{retry}                           : <undefined>
opt{server}                          : <undefined>
opt{ssl}                             : <undefined>
opt{ssl_ca_dir}                      : <undefined>
opt{ssl_ca_file}                     : <undefined>
opt{syslog}                          : <undefined>
opt{test}                            : <undefined>
opt{timeout}                         : <undefined>
opt{use}                             : <undefined>
opt{usev4}                           : <undefined>
opt{usev6}                           : <undefined>
opt{verbose}                         : 1
opt{web}                             : <undefined>
opt{web-skip}                        : <undefined>
opt{web-ssl-validate}                : <undefined>
opt{webv4}                           : <undefined>
opt{webv4-skip}                      : <undefined>
opt{webv6}                           : <undefined>
opt{webv6-skip}                      : <undefined>
=== globals ====
globals{daemon}                      : 60
globals{debug}                       : 1
globals{mail}                        : root
globals{mail-failure}                : root
globals{pid}                         : /usr/local/var/run/ddclient.pid
globals{quiet}                       : 0
globals{ssl}                         : 1
globals{syslog}                      : 1
globals{verbose}                     : 1
=== config ====
=== cache ====

**Comment by SuperSandro2000** [comment] 2022-09-11 00:18
> ./autogen failed

How? Did you try to search the internet for help?

> or could you push it to freebsd.ports?

No because I don't have a plan about bsd.

**Comment by devang** [comment] 2022-10-02 22:08
Installing from git and setting user=token with password='read/write zone token' works for me, but I had to manually create an A record with 0.0.0.0 first in Cloudflare.

**Closed** 2022-10-20 18:09 UTC
Labels: bug, fixed-in-next-release

**Comment by andrp92** [comment] 2023-02-09 02:28
> You are missing some packages. I am trying to upload a generated tarball in some days.
> 
> ```
> apt install autoconf automake
> ```

It seems like a lot of people are having the same issue with this packages. Can you add that note to the installation docs? It would be really helpful.

**Comment by andrp92** [comment] 2023-02-09 03:22
Same issue using api token:
SENDING:  Connection: close
SENDING:  Content-Type: application/json
SENDING:  Authorization: Bearer <sometoken>,
SENDING:
RECEIVE:  HTTP/1.1 400 Bad Request
RECEIVE:  Date: Thu, 09 Feb 2023 03:17:52 GMT
RECEIVE:  Content-Type: application/json
RECEIVE:  Transfer-Encoding: chunked
RECEIVE:  Connection: close
RECEIVE:  CF-Ray: 7969745cabb8db01-MIA
RECEIVE:  Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
RECEIVE:  Expires: Sun, 25 Jan 1981 05:00:00 GMT
RECEIVE:  Set-Cookie: __cflb=0H28vgHxwvgAQtjUGUFqYFDiSDreGJnUjwD3WY9iej7; SameSite=Lax; path=/; expires=Thu, 09-Feb-23 05:47:53 GMT; HttpOnly
RECEIVE:  Strict-Transport-Security: max-age=31536000
RECEIVE:  CF-Cache-Status: DYNAMIC
RECEIVE:  Pragma: no-cache
RECEIVE:  X-Content-Type-Options: nosniff
RECEIVE:  X-Frame-Options: SAMEORIGIN
RECEIVE:  Set-Cookie: __cfruid=42da54887315b865d500e68b4b20533016b8b9ca-1675912672; path=/; domain=.api.cloudflare.com; HttpOnly; Secure; SameSite=None
RECEIVE:  Server: cloudflare
RECEIVE:
RECEIVE:  bc
RECEIVE:  {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6111,"message":"Invalid format for Authorization header"}]}],"messages":[],"result":null}
RECEIVE:  0
RECEIVE:
FAILED:   updating \: Could not connect to api.cloudflare.com/client/v4.

**Comment by SuperSandro2000** [comment] 2023-02-09 21:32
> Can you add that note to the installation docs?

That is already added https://github.com/ddclient/ddclient#manual-installation

**Comment by itzjacki** [comment] 2023-06-06 21:19
Same issue as people above. Works with global key, but when using an API token with the correct permissions and setting login=token, it breaks - giving me a format error on the headers.

I am on 3.9.1 however, but since it doesn't seem to be working for others, I'll stay on 3.9.1 with my global key for now.

**Comment by MDKAOD** [comment] 2023-06-24 19:44
I have a hint to add on the "Could not connect to api.cloudflare.com/client/v4" error.

I was only able to get ddclient to work with an API token as long as the default template was essentially untouched. 

After removing the custom token, and recreating it. Not adding a zone and instead choosing 'All zones" and not adding a client address filter, the dns zones updated instantly.

![image](https://github.com/ddclient/ddclient/assets/1223587/55600828-6b06-45a4-857f-9c05d5648e58)
