### ISSUE TITLE
ddclient spams cloudflare (and maybe other providers)

### ISSUE THREAD

**Issue by Saturn49** [ddclient/ddclient#481] opened 2022-12-11 04:26 UTC
It seems the (somewhat incomplete) conversion from "use" to "usev4" and "usev6" has left some providers spamming on every update instead of using the cache to prevent updating.  

The issue stems from the use of 'status', 'status-v4', and 'status-v6'. 

`nic_cloudflare_update()`, for instance, never sets the 'status' key, so it is left as 'no-connect'.  However, this variable is checked in `nic_updateable()`, because `$use` cannot be set to 'disabled' - the parser doesn't allow it.  The result is that even if a cloudflare update was successful last time, it is updated again because 'status' was left at `no-connect`.

I have a patch that works for my usage, by simply adding 

```
                    if($ipv == "4") {
                        $config{$domain}{"ip"} = $ip;
                        $config{$domain}{"status"} = 'good';
                    }
```
inside the 
```
if ($response && $response->{result}) {
    success("updating %s: IPv$ipv address set to %s", $domain, $ip);
```
block.  However, I found this pattern elsewhere (freedns and hetzner).

So I'd like to ask the regular contributers, what is the contract for the update functions during this transition to supporting ipv6?  Should every update function be setting 'status-ipv4' and 'status'?  Or maybe there's a better, more centralized place to combine these?

**Comment by zelch** [comment] 2022-12-19 09:25
Alright, looking through the code a bit...

I'm thinking that the core handling of 'use' is broken, but that we can probably make everything reasonably sane with some straight forward logic changes, and some search and replace.

I propose:

*  If usev4 and usev6 are not specified, use becomes a direct alias for usev4.  If usev4 or usev6 is specified, use is outright ignored.
* All instances of setting status are replaced with updating status-ipv4.
* All checks for use are either removed, or replaced with checks for usev4.
* When reading the cache, any instances of status are replaced with status-ipv4.
* For processing the ip argument, we check to see if we are passed an IPv4 address or an IPv6 address, and then treat it as either ipv4 or ipv6 respectively.
* And we replace all of the references to use, ip, and status in any of the nic_ subroutines with the ipv4 versions.

Can anyone see any points where this would cause a regression?

The only case I can think of is one where a protocol allows either an IPv4 or an IPv6 address to be used, and figures out if it should be a A or an AAAA record itself, and the user is expecting an IPv6 only update.

That's not really ideal, but neither is the current behavior where, if you don't specify use, useipv4, or useipv6, and you specify a protocol like cloudflare that supports the new statuses and not the old statuses, we just spam endlessly.

Hm, alright, I _can_ think of one other alternative, add a field to services that indicates if a given service uses the new or the old style, and ignore use for services that use the new style, and ignore usev4 and usev6 for services that use the old style.

And if ip or use is defined for a new style service, set both usev4 and usev6, and map ip based on if it is an ipv4 address or an ipv6 address.

Thoughts?

**Comment by Saturn49** [comment] 2022-12-27 06:29
Seems like a good plan to me.  Take my opinion with a grain of salt as I'm not (yet) a contributor, but your first plan seems to solve the current issue and seems to get closer to the deprecation of the old style parameters.  Adding a parameter to each service would also work, but creates more technical debt to remove later.

**Comment by SuperSandro2000** [comment] 2023-01-13 17:26
> I'm thinking that the core handling of 'use' is broken, but that we can probably make everything reasonably sane with some straight forward logic changes, and some search and replace.

That is probably true but I don't have any interest myself to majorly refactor the pile of perl code. 

> Can anyone see any points where this would cause a regression?

I have forgotten most ddclient internals, so I cannot answer that.

**Comment by SuperSandro2000** [comment] 2023-07-04 11:15
dupe of #431

**Closed by SuperSandro2000** 2023-07-04 11:15 UTC
Labels: bug, provider, help-wanted
