### ISSUE TITLE
`use=web` default no longer works as https://checkip.dyndns.org is no longer reachable anymore 

### ISSUE THREAD

**Issue by wheelerlaw** [ddclient/ddclient#597] opened 2023-11-14 12:26 UTC
https://checkip.dyndns.org is not reachable (the plain HTTP one is though). The default option for `use=web` should be changed to one that is working.

**Comment by LenardHess** [comment] 2023-11-23 11:09
ddclient will choose http/https depending on the URL by default.
There is the option to force every connection to use HTTPS - the `-ssl` option.

Did your configuration have `https` in the URL or did you set the `-ssl` parameter?

**Comment by bryanhorstmann** [comment] 2023-11-24 07:16
I can confirm I'm seeing the same thing on `3.11.x` with `checkip.dyndns.com`. Here are my tests:

With the following config (from `3.10`):
```
ssl=yes
use=web, web=checkip.dyndns.com/, web-skip='IP Address'
```
I get the following:
```
WARNING:  CURL error (28) Operation timeout. The specified time-out period was reached according to the conditions.
WARNING:  curl cannot connect to https://checkip.dyndns.com using IPv4
WARNING:  Could not determine an IP for <my domain>
```

With this config:
```
ssl=yes
usev4=webv4, webv4=checkip.dyndns.com/, web-skip='IP Address'
```
I get the following:
```
WARNING:  CURL error (28) Operation timeout. The specified time-out period was reached according to the conditions.
WARNING:  curl cannot connect to https://checkip.dyndns.com using IPv4
WARNING:  Could not determine an IP for <my domain>
```

With this config:
```
ssl=yes
usev4=webv4, webv4=https://checkip.dyndns.com/, web-skip='IP Address'
```
I get the following:
```
WARNING:  CURL error (28) Operation timeout. The specified time-out period was reached according to the conditions.
WARNING:  curl cannot connect to https://checkip.dyndns.com using IPv4
WARNING:  Could not determine an IP for <my domain>
```

With this config:
```
ssl=no
usev4=webv4, webv4=http://checkip.dyndns.com/, web-skip='IP Address'
```
I get the following:
```
WARNING:  updating <my domain>: nochg: No update required; unnecessary attempts to change to the current address are considered abusive
```

If I revert back to `3.10` with my original config file it works as expected.

**Comment by BraxtonLowers** [comment] 2023-11-29 05:13
I recently observed the same issue. Default ddclient.conf sets https as the only option because of the config line
`ssl=yes                                  # use ssl-support.  Works with`
My workaround (probably sub-optimal though, better solution would be to change default use=web) was to turn off ssl in the config, which allowed http://checkip.dyndns.org. Using 
`ssl=no`

Note that this still used SSL when reaching out to my DNS provider according to `sudo  ddclient -daemon=0 -debug -verbose -noquiet` so API keys were never send over plaintext.

**Comment by brianread108** [comment] 2023-11-30 08:52
Also see #309

**Comment by LenardHess** [comment] 2023-11-30 22:18
The current `ssl` flag acts as a "Force SSL on everything" flag. It might be worthwhile to have separate flags for "Use SSL by default unless specified (aka. any URL without HTTP/HTTPS scheme prefix) and another flag for "Force HTTP scheme to use HTTPS - which might not work"

I haven't dug deep into this but I'd assume that every single URL passed to ddclient can be made either HTTP or HTTPS so the SSL support is selectable.  In that case the SSL flag is merely a convenience flag to auto-upgrade everything to HTTPS.
If there are URLs hardcoded to HTTP, that needs further investigation.

**Comment by KLelong** [comment] 2023-12-03 09:02
FWIW, I have intermittent problems just pinging checkip.dyndns.org. 
I checked because I configured ddclient to send messages. Since a while I get intermittent messages like
```
WARNING:  cannot connect to checkip.dyndns.org:80 socket: IO::Socket::INET: Bad hostname 'checkip.dyndns.org'
WARNING:  found neither ipv4 nor ipv6 address
```
and
`WARNING:  found neither ipv4 nor ipv6 address
`
I just changed to loopia, will await results.

**Comment by LenardHess** [comment] 2024-01-04 15:44
With #608 merged you can now force the usage of HTTP by prefixing the URL with `http://` even when the `ssl` config option or command line option is enabled

**Closed by LenardHess** 2024-01-04 15:44 UTC
Labels: needinfo
